name: Push
on: [push]
jobs:
  push:
    name: Test and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bazelisk
        run: curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-linux-amd64" | install -D /dev/stdin "${GITHUB_WORKSPACE}/bin/bazel"
      - run: bazel test //...
      - uses: azure/docker-login@v1
        if: github.ref == 'refs/heads/master'
        with:
          username: uhthomas
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.CR_PAT }}
      - run: bazel run //cmd/kipp:push
        if: github.ref == 'refs/heads/master'
